<?php $collection = $this->getTestimonials() ?>
<?php 
	if($this->getViewMode()){
		$viewMode = $this->getViewMode();
	}
	else{
		$viewMode = 'grid';
	}
?>
<?php if(count($collection)>0): ?>
	<div class="testimonial-container block">
		<?php if($this->getTitle()!=''): ?>
			<div class="block-title">
				<h2 class="title-name"><?php echo $this->getTitle() ?></h2>
			</div>
		<?php endif ?>
		<?php if($viewMode=='grid'): ?>
			<div class="owl-carousel testimonials-carousel block-content" data-plugin-options="{'items': 1, 'autoHeight': true, 'controlNav': true }" id="testimonials-carousel">
				<?php foreach($collection as $_item): ?>
					<div class="testimonial-item">
						<div class="testimonial-author">
						<?php if($_item->getAvatar()): ?>
							<div class="img-thumbnail img-thumbnail-small">							
								<img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>testimonial/<?php echo $_item->getAvatar() ?>" alt="">							
							</div>
						<?php endif;?>
							
						</div>
						<div class="testimonial-content">
							<div class="testimonial-icon"><i class="fa fa-quote-left"></i></div>
							<div class="desc">
								<?php echo $_item->getContent() ?>
								<p class="name-super"><?php echo $this->__('By ') ?><strong><?php echo $_item->getName() ?></strong><span><?php echo $_item->getInformation() ?></span></p>
							</div>
						</div>
					</div>
				<?php endforeach ?>
			</div>
		
		<script type="text/javascript">
			initSlider('testimonials-carousel', 1, false, false, false, true);
		</script>
		<?php else: ?>
			<div class="testimonials-list">
				<?php foreach($collection as $_item): ?>
					<div class="testimonial-item">
						<div class="testimonial-author">
						<?php if($_item->getAvatar()): ?>
							<div class="img-thumbnail img-thumbnail-small">							
								<img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>testimonial/<?php echo $_item->getAvatar() ?>" alt="">							
							</div>
						<?php endif;?>
							<p><strong><?php echo '- '.$_item->getName() ?></strong><span><?php echo $_item->getInformation().' -' ?></span></p>
						</div>
						<div class="testimonial-content">
							<p><?php echo $_item->getContent() ?></p>
						</div>
					</div>
				<?php endforeach ?>
			</div>
		<?php endif ?>
	</div>
<?php endif ?>
