<?php
/* * ****************************************************
 * Package   : Brand
 * Author    : HIEPNH
 * Copyright : (c) 2015
 * ***************************************************** */
?>
<?php
$_productCollection = $this->getLoadedProductCollection();
$_helper = $this->helper('catalog/output');
$model = $this->getBrand();
$helper = Mage::helper('brand');
?>
<?php
	$panelHelper = $this->helper('mpanel');
	$size = $panelHelper->convertRatioToSize();
?>
<?php if ($model->getTitle() != ''): ?>
    <div class="page-title category-title">
        <h1><?php echo $model->getTitle(); ?></h1>
    </div>
<?php endif; ?>

<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>

<?php if ($model->getImage() != ''): ?>
    <p class="category-image">
        <img class="img-responsive"
             title="<?php echo $model->getTitle(); ?>" alt="<?php echo $model->getTitle(); ?>"
             src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB) . 'media/' . $model->getImage(); ?>">
    </p>
<?php endif; ?>

<?php if ($model->getDescription() != ''): ?>
    <div class="category-description std">
        <p><?php echo $model->getDescription(); ?></p>
    </div>
<?php endif; ?>

<?php if (!$_productCollection->count()): ?>
    <p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php else: ?>
    <div class="category-products">
        <?php echo $this->getToolbarHtml() ?>
        <?php // List mode ?>
        <?php if ($this->getMode() != 'grid'): ?>
            <?php $_iterator = 0; ?>
            <ol class="products-list row" id="products-list">
                <?php foreach ($_productCollection as $_product): ?>
                    <li class="item<?php if (++$_iterator == sizeof($_productCollection)): ?> last<?php endif; ?>">
                        <?php // Product Image ?>
						<div class="col-md-3 col-sm-6 col-xs-12">
							<a href="<?php echo $_product->getProductUrl() ?>"
								title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>"
								class="product-image"><img class="img-responsive"
                                src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($size['width'], $size['height']); ?>"
                                alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>"/></a>
						</div>
						<div class="col-md-9 col-sm-6 col-xs-12">
							<div class="f-fix">
								<?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
                                <h2 class="product-name">
									<a href="<?php echo $_product->getProductUrl() ?>"
									   title="<?php echo $_productNameStripped; ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?></a>
                                </h2>
								<?php echo $this->getPriceHtml($_product, true) ?>
								<?php //if ($_product->getRatingSummary()): ?>
                                    <?php echo $this->getReviewsSummaryHtml($_product) ?>
                                <?php //endif; ?>
								<div class="controls">
									<div class="add-to-cart">
										<?php if ($_product->isSaleable()): ?>
                                        <button type="button" title="<?php echo $this->__('Add to Cart') ?>"
                                                class="btn btn-primary btn-xs btn-cart"
                                                onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')">
                                            <span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
										<?php else: ?>
										<p class="availability out-of-stock">
											<span><?php echo $this->__('Out of stock') ?></span></p>
										<?php endif; ?>
									</div>
									<ul class="icon-links">
										<?php if($this->helper('core')->isModuleEnabled('MGS_QuickView') && Mage::getStoreConfig('quickview/general/active')): ?>
												<li><button type="button" onclick="quickView('<?php echo $_product->getProductUrl() ?>'); return false;"><em class="fa fa-search"></em></button></li>
											<?php endif ?>
										<?php if ($this->helper('wishlist')->isAllow()) : ?>
											<li><button type="button" title="<?php echo $this->__('Add to Wishlist') ?>" href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>"
                                           class="link-wishlist"><em class="fa fa-heart-o"></em></button></li>
										<?php endif; ?>
										<?php if ($_compareUrl = $this->getAddToCompareUrl($_product)): ?>
											<li><button type="button" title="<?php echo $this->__('Add to Compare') ?>" href="<?php echo $_compareUrl ?>"
                                                class="link-compare"><em class="fa fa-retweet"></em></button></li>
										<?php endif; ?>
									</ul>
								</div>
								<div class="desc std">
                                    <?php echo $_helper->productAttribute($_product, $_product->getDescription(), 'description') ?>
                                </div>
							</div>
						</div>
                    </li>
                <?php endforeach; ?>
            </ol>
            <script type="text/javascript">decorateList('products-list', 'none-recursive')</script>

        <?php else: ?>

            <?php // Grid Mode ?>

            <?php $_collectionSize = $_productCollection->count() ?>
            <?php $_columnCount = $this->getColumnCount(); ?>
            <?php
            $i = 0;
            foreach ($_productCollection as $_product):
                ?>
                <?php if ($i++ % $_columnCount == 0): ?>
                    <ul class="products-grid row">
                    <?php endif ?>
                    <li class="col-md-3 col-sm-6 col-xs-12 item<?php if (($i - 1) % $_columnCount == 0): ?> first<?php elseif ($i % $_columnCount == 0): ?> last<?php endif; ?>">
                        <div class="product-content">
							<div class="product-top">
								<a href="<?php echo $_product->getProductUrl() ?>"
								title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>"
								class="product-image"><img class="img-responsive"
                                src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($size['width'], $size['height']); ?>"
                                alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>"/></a>
								<div class="controls">
									<ul class="icon-links">
										<?php if ($this->helper('wishlist')->isAllow()) : ?>
											<li><button type="button" title="<?php echo $this->__('Add to Wishlist') ?>" href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>"
                                           class="link-wishlist"><em class="fa fa-heart-o"></em></button></li>
										<?php endif; ?>
										<?php if($this->helper('core')->isModuleEnabled('MGS_QuickView') && Mage::getStoreConfig('quickview/general/active')): ?>
												<li class="li-quickview"><button type="button" onclick="quickView('<?php echo $_product->getProductUrl() ?>'); return false;"><em class="fa fa-search"></em></button></li>
											<?php endif ?>
										<?php if ($_compareUrl = $this->getAddToCompareUrl($_product)): ?>
											<li><button type="button" title="<?php echo $this->__('Add to Compare') ?>" href="<?php echo $_compareUrl ?>"
                                                class="link-compare"><em class="fa fa-retweet"></em></button></li>
										<?php endif; ?>
									</ul>
								</div>
								<div class="rating">
									<?php if ($_product->getRatingSummary()): ?>
										<?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
									<?php endif; ?>
								</div>
							</div>
							<div class="product-desc">
								<h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>"
                                    title="<?php echo $this->stripTags($_product->getName(), null, true) ?>">
									<?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></h2>
								<?php echo $this->getPriceHtml($_product, true) ?>
								<?php if ($_product->isSaleable()): ?>
									<button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="btn btn-cart btn-default btn-xs"
											onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')">
											<span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
								<?php else: ?>
									<p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
								<?php endif; ?>
							</div>
						</div>
                    </li>
                    <?php if ($i % $_columnCount == 0 || $i == $_collectionSize): ?>
                    </ul>
                <?php endif ?>
            <?php endforeach ?>
            <script
            type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd', 'even', 'first', 'last'])</script>
        <?php endif; ?>

        <div class="toolbar-bottom col-md-12 col-sm-12 col-xs-12">
            <?php echo $this->getToolbarHtml() ?>
        </div>
    </div>
<?php endif; ?>