<?php $title = $this->getTitle(); ?>
<?php if($title==''){ $title = Mage::getStoreConfig('social/twitter/twitter_title'); } ?>
<?php $user = $this->getUser(); ?>
<?php $count = $this->getCount(); ?>
<?php $truncate = $this->getTruncate(); ?>
<div class="block">
	<?php if($title!=''): ?><div class="block-title"><h2 class="title-name"><?php echo $title ?></h2></div><?php endif ?>
	<div class="block-content">
		<?php if(Mage::getStoreConfig('social/twitter/token')!='' && Mage::getStoreConfig('social/twitter/token_secret') !='' && Mage::getStoreConfig('social/twitter/client_id')!='' && Mage::getStoreConfig('social/twitter/client_secret') !=''): ?>
			<?php echo $this->helper('mpanel/social')->getLastTwitter($user, $count, $truncate); ?>
		<?php else: ?>
			<div class="alert alert-danger">
				<p><?php echo $this->__('Please update your twitter settings first.') ?></p>
			</div>
		<?php endif ?>
	</div>
</div>


