<?php if (Mage::getStoreConfig('deals/general/enabled')): ?>
	<div class="category-image">
		<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('cetus_deals_block_top')->toHtml(); ?>
	</div>
    <div class="page-title">
        <h1><?php echo Mage::getStoreConfig('deals/deals_page/title') ?></h1>
    </div>
    <?php
    $layout = Mage::getSingleton('core/layout');
    $productCollection = $this->getProductCollection();
    $toolbar = $this->getToolbarBlock();
    $pager = $layout->createBlock('page/html_pager');
    $toolbar->setChild('product_list_toolbar_pager', $pager);
    $toolbar->setCollection($productCollection);
    
    $toolbar->setMode($this->getMode());
	$toolbar->setTemplate('mgs/deals/toolbar.phtml');
	?>
	<div class="top-deals-toolbar"><?php echo $toolbar->toHtml(); ?></div>
    <?php if (count($productCollection) > 0): ?>
	<div class="category-products">
        <?php if ($this->getMode() != 'grid'): ?>
            <ul class="products-list rating-category">
                <?php foreach ($productCollection as $product): ?>
                    <?php $_product = Mage::getModel('catalog/product')->load($product->getId()) ?>
                    <li class="item">
                        <div class="product-content">
							<div class="row">
								<div class="col-md-3 col-sm-6 col-xs-12">
									<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image">
										<img class="img-responsive" src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image'); ?>" alt="<?php echo $this->htmlEscape($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
									</a>
									<div class="deals-hot">
										<p><?php echo $this->__('Save') ?></p>
										<?php $save = $_product->getPrice() - $_product->getFinalPrice() ?>
										<?php $percent = round(($save * 100) / $_product->getPrice(), 1) ?>
										<?php echo $percent ?><sup>%</sup>
									</div>
								</div>
								<div class="col-md-6 col-sm-6 col-xs-12">
									<div>
										<div class="f-fix">
											<h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($this->getImageLabel($_product, 'small_image'), null, true) ?>"><?php echo $_product->getName() ?></a></h2>
											<div class="price-box">
												<?php echo $this->getPriceHtml($_product, true) ?>
											</div>
											<div class="rating">
											<?php //if($_product->getRatingSummary()): ?>
												<?php echo $this->getReviewsSummaryHtml($_product) ?>
											<?php //endif; ?>
											</div>
											<div class="desc std">
												<h2>Quick Overview:</h2>
												<p><?php echo Mage::helper('core/string')->truncate($_product->getDescription()); ?></p>
											</div>
										</div>
									</div>
								</div>
								<div class="col-md-3 col-sm-6 col-xs-12">
									<div class="deals-info deal-timer-white">
										<?php echo $this->getLayout()->createBlock('deals/deals')->setTemplate('mgs/deals/list.phtml')->setProductId($_product->getId())->toHtml(); ?>
										<div class="item-info">
											<div class="sold">
												<?php echo $this->__('Sold:') ?> <span><?php echo $this->getSold($_product->getId()) ?></span>
											</div>
											<div class="item-left">
												<?php $itemLeft = $this->getItemLeft($_product->getId()); ?>
												<?php if ($itemLeft != ''): ?>
													<?php if ($itemLeft > 1): ?>
														<?php echo $this->__('Items left:') ?> <span><?php echo $itemLeft ?></span>
													<?php else: ?>
														<?php echo $this->__('Item left:') ?> <span><?php echo $itemLeft ?></span>
													<?php endif ?>
												<?php else: ?>
													<?php echo $this->__('Items left:') ?> <span><?php echo $this->__('Unlimited') ?></span>
												<?php endif ?>
											</div>
										</div>
										<form action="<?php echo $this->getAddToCartUrl($_product) ?>" method="post" id="product_addtocart_form_<?php echo $_product->getId(); ?>">
											<div class="deal-add-cart">
												<input name="qty" type="number" class="input-text qty addcart-qty" id="addcartqty" maxlength="12" value="<?php echo $this->getMinimalQty($_product) ?>" />
												<div class="add-to-cart">
													<button class="btn-cart btn btn-primary btn-lg btn-full" onclick="productAddToCartForm_<?php echo $_product->getId(); ?>.submit();"><span><?php echo $this->__('Buy Now') ?></span></button>
												</div>
											</div>
										</form>
										<script type="text/javascript">
											var productAddToCartForm_<?php echo $_product->getId(); ?> = new VarienForm('product_addtocart_form_<?php echo $_product->getId(); ?>');
											productAddToCartForm_<?php echo $_product->getId(); ?>.submit = function() {
												if (this.validator.validate()) {
													this.form.submit();
												}
											}.bind(productAddToCartForm_<?php echo $_product->getId(); ?>);
										</script>
									</div>
								</div>
							</div>
                        </div>
                    </li>
                <?php endforeach ?>
            </ul>
        <?php else: ?>
            <?php $_collectionSize = $productCollection->count() ?>
            <?php $_columnCount = $this->getColumnCount(); ?>
            <?php
            $i = 0;
            foreach ($productCollection as $product):
                $_product = Mage::getModel('catalog/product')->load($product->getId());
                ?>
                <?php if ($i++ % $_columnCount == 0): ?>
                    <ul class="products-grid rating-category row">
                    <?php endif ?>
                    <li class="item<?php if (($i - 1) % $_columnCount == 0): ?> first<?php elseif ($i % $_columnCount == 0): ?> last<?php endif; ?> col-md-4 col-sm-4 col-xs-12">
						<div class="product-sale">
							<div class="product-content">
								<div class="product-hot">
									<div class="count-deals-content">
										<?php echo $this->getLayout()->createBlock('deals/deals')->setTemplate('mgs/deals/list.phtml')->setProductId($_product->getId())->toHtml(); ?>
										
										<div class="deals-hot">
											<?php $save = $_product->getPrice() - $_product->getFinalPrice() ?>
											<?php $percent = round(($save * 100) / $_product->getPrice(), 1) ?>
											<?php echo $percent ?>%
											<p><?php echo $this->__('OFF') ?></p>
										</div>
									</div>
									<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img class="img-responsive" src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image'); ?>" alt="<?php echo $this->htmlEscape($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
								</div>
								<div class="product-desc">
									<h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_product->getName(); ?></a></h2>
									<div class="price-box">
										<?php echo $this->getPriceHtml($_product, true) ?>
									</div>
								</div>
								<!--<?php if ($_product->getRatingSummary()): ?>
									<?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
									<?php endif; ?>-->
								<div class="add-to-cart">
									<?php if ($_product->isSaleable()): ?>
										<button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="btn-cart btn btn-primary btn-sm btn-full" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>');"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
									<?php else: ?>
										<p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
									<?php endif; ?>
								</div>
							</div>
						</div>
                    </li>
                    <?php if ($i % $_columnCount == 0 || $i == $_collectionSize): ?>
                    </ul>
                <?php endif ?>
            <?php endforeach ?>
            <script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd', 'even', 'first', 'last']);</script>
        <?php endif; ?>
    <?php endif; ?>
	</div>
    <div class="bottom-deals-toolbar"><?php echo $toolbar->toHtml(); ?></div>
	
<?php endif; ?>