<?php
$categories = $this->getCategoryCollection();
$panelHelper = $this->helper('mpanel');
$size = $panelHelper->convertRatioToSize($this->getProductRatio());
if ($this->getColumn()) {
    $col = $this->getColumn();
} else {
    $col = 3;
}

$col = $panelHelper->convertColRowCustom($col);
?>
<?php if (Mage::getStoreConfig('mpanel/catalog/featured') != ''): ?>
    <?php if (count($categories) > 0): ?>
        <div class="featured-category-products featured-category-products-tabs category-tabs">
            <?php if ($this->getTitle() != ''): ?>
                <div class="carousel_wrapper title-categories">
                    <p class="title">
                        <span><?php echo $this->getTitle() ?></span>
                    </p>
                </div>
            <?php endif ?>
            <div class="category-product-item">
                <div class="col-md-12">
                    <div class="row">
                        <div class="tabs-container">
                            <ul class="nav nav-tabs tab-menu" role="tablist">
                                <?php $i = 0;
                                foreach ($categories as $_category): $i++; ?>										
                                    <li<?php if ($i == 1): ?> class="active"<?php endif ?> role="presentation">
                                        <a href="#section-flip-<?php echo $_category->getId(); ?>" role="tab" data-toggle="tab" aria-expanded="false" >
                                            <span><?php echo $_category->getName() ?></span>

                                        </a>
                                    </li>
                                <?php endforeach ?>
                            </ul>
                            <div class="products tab-content">
                                <?php $i = 0;
                                foreach ($categories as $_category): $i++; ?>
                                    <?php $products = $this->getProductByCategory($_category) ?>
                                        <div role="tabpanel" class="tab-pane<?php if ($i == 1): ?> active<?php endif ?>" id="section-flip-<?php echo $_category->getId(); ?>">
                                            <div class="products-grid row">
                                                <?php if (count($products) > 0): ?>
                                                <?php foreach ($products as $_product): ?>
                    <?php //$_product = Mage::getModel('catalog/product')->load($_product)  ?>
                                                    <div class="item col-md-<?php echo $col ?> col-sm-6 col-xs-12">
                                                        <div class="product-content">
                                                            <div class="product-top">
                                                                <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>" class="product-image">
                                                                    <img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($size['width'], $size['height']) ?>" alt="<?php echo $this->stripTags($_product->getName(), null, true) ?>" class="img-responsive"/>

                                                                </a>
                                            <div class="label-product">
						<?php echo $panelHelper->getProductLabel($_product) ?>
                                            </div>
                                                                <div class="controls">
                                                                    <ul class="icon-links">

                                                                        <?php if ($this->helper('wishlist')->isAllow()) : ?>
                                                                            <li><button type="button" title="<?php echo $this->__('Add to Wishlist') ?>" onclick="setLocation('<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>')"><em class="fa fa-heart"></em></button></li>
                                                                        <?php endif; ?>
                                                                        <?php if ($this->helper('core')->isModuleEnabled('MGS_QuickView') && Mage::getStoreConfig('quickview/general/active')): ?>
                                                                            <li class="li-quickview"><button type="button" title="<?php echo $this->__('Quickview') ?>" class="btn-quickview quick-view" onclick="quickView('<?php echo $_product->getProductUrl() ?>');
                                                                                    return false;"><em class="fa fa-search"></em></button></li>
                                                                        <?php endif ?>
                                                                        <?php if ($_compareUrl = $this->getAddToCompareUrl($_product)): ?>
                                                                            <li><button type="button" title="<?php echo $this->__('Add to Compare') ?>" onclick="setLocation('<?php echo $_compareUrl ?>')"><em class="fa fa-retweet"></em></button></li>
                    <?php endif; ?>

                                                                    </ul>
                                                                </div>
                    <?php echo $this->getLayout()->createBlock('review/helper')->getSummaryHtml($_product, 'short'); ?>
                                                            </div>
                                                            <div class="product-desc">
                                                                <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>)"><?php echo $this->stripTags($_product->getName(), null, true) ?></a></h2>
                                                                <?php echo $this->getPriceHtml($_product, true, '-widget-new-grid') ?>
                                                                <?php if ($_product->isSaleable()): ?>
                                                                    <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="btn btn-cart btn-default btn-xs" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><?php echo $this->__('Add to Cart') ?></button>
                    <?php endif; ?>
                                                            </div>

                                                        </div>
                                                    </div>
                                        <?php endforeach ?>
                                                <?php else: ?>
                                                <div class="no-product-display col-md-12 col-sm-12 col-xs-12">
                                                    <p class="alert alert-danger "><?php echo $this->__('There are no products matching the selection.') ?></p>
                                                </div>
                                                <?php endif; ?>
                                            </div>
                                        </div>
                                        
        <?php endforeach ?>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    <?php endif ?>
<?php else: ?>
    <div class="alert alert-danger"><?php echo $this->__('Please set "Featured Product Attribute"') ?></div>
<?php endif ?>
