<?php $megaMenu = $this->getMegamenuItems(); ?>
<?php if(count($megaMenu)>0):?>
<?php
if ($this->getTitle() != '') {
    $title = $this->getTitle();
}
?>
<?php if(isset($title)){
?>
<div class="block-title">
    <h2 class="title-name"><?php echo $this->__($title) ?></h2>
</div>
<?php } ?>
<ul id="vertical-menu-<?php echo $this->getMenuId()?>" class="mega-nav menu-category">
	<?php if(count($megaMenu)>0): ?>
		<?php $i=0; foreach($megaMenu as $item): $i++ ?>
			<li class="<?php echo $this->getClass($item) ?> vertical-<?php echo $item->getColumns()?>-columns">
				<?php echo $this->getMenuHtml($item) ?>
			</li>
		<?php endforeach ?>
	<?php endif ?>
</ul>
<?php endif ?>