<?php if (($_products = $this->getProductCollection()) && $_products->getSize()): ?>
    <?php $helper = $this->helper('mpanel') ?>
    <?php $size = $helper->convertRatioToMinSize($this->getProductRatio()) ?>
    <div class="block product-list-block new-list box-collateral">
        <?php if ($this->getTitle() != ''): ?>
            <div class="block-title">
                <h2 class="title-name"><?php echo $this->getTitle() ?></h2>
            </div>
        <?php endif ?>
        <div class="block-content">
            <?php
            $i = 0;
            foreach ($_products as $_product):
                ?>
                <?php $_product = Mage::getModel('catalog/product')->load($_product->getId()) ?>
                <div class="product-content">
                    <div class="product-top">
                        <a class="product-image" href="<?php echo $_product->getProductUrl() ?>">
                            <img alt="<?php echo $this->stripTags($_product->getName(), null, true) ?>" src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($size['width'], $size['height']) ?>" class="img-responsive" />

                        </a>
                        <?php echo $helper->getProductLabel($_product) ?>
                    </div>
                    <div class="product-desc">
                        <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>">							
                                <?php echo $this->helper('catalog/output')->productAttribute($_product, $_product->getName(), 'name') ?>
                            </a></h2>
                        <?php echo $this->getPriceHtml($_product, true) ?>

                        <div class="controls">
                            <ul class="icon-links">
                                <?php if ($_product->isSaleable()): ?>
                                    <li>
                                        <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="btn btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><i class="fa fa-shopping-cart"></i></button>
                                    </li>
                                <?php endif; ?>
                                <?php if ($this->helper('core')->isModuleEnabled('MGS_QuickView') && Mage::getStoreConfig('quickview/general/active')): ?>
                                    <li class="li-quickview"><button type="button" title="<?php echo $this->__('Quickview') ?>" class="btn-quickview quick-view" onclick="quickView('<?php echo $_product->getProductUrl() ?>');
                                                        return false;"><em class="fa fa-search"></em></button></li>
                                                                 <?php endif ?>
                                                                 <?php if ($this->helper('wishlist')->isAllow()) : ?>
                                    <li><button type="button" title="<?php echo $this->__('Add to Wishlist') ?>" onclick="window.location.href = '<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>'"><em class="fa fa-heart"></em></button></li>
                                <?php endif; ?>
                                <?php if ($_compareUrl = $this->getAddToCompareUrl($_product)): ?>
                                    <li><button type="button" title="<?php echo $this->__('Add to Compare') ?>" onclick="window.location.href = '<?php echo $_compareUrl ?>'"><em class="fa fa-retweet"></em></button></li>
                                        <?php endif; ?>
                            </ul>
                        </div>
                    </div>
                </div>
            <?php endforeach ?>
        </div>
    </div>
<?php else: ?>
    <div class="block product-list-block featured-list box-collateral">
        <?php if ($this->getTitle() != ''): ?>
            <div class="block-title">
                <h2 class="title-name"><?php echo $this->getTitle() ?></h2>
            </div>
        <?php endif ?>
        <div class="block-content">
            <div class="alert alert-danger no-product-display">
                <p><?php echo $this->__('There are no products matching the selection.') ?></p>
            </div>
        </div>
    </div>
<?php endif; ?>