<?php if(Mage::getStoreConfig('deals/general/enabled')): ?>
<?php
    $_productCollection=$this->getProductCollection();
    $_helper = $this->helper('catalog/output');
	$helper = $this->helper('mpanel');
	$size = $helper->convertRatioToSize($this->getProductRatio());
	$widgetId = $this->getWidgetId();
?>
<?php if(count($_productCollection)>0): ?>
    <?php if($this->getTitle()!=''): ?>	
	<div class="title-categories">
        <p class="title">
            <span><?php echo $this->getTitle() ?></span>
        </p>
	</div>
    <?php endif ?>
    <?php $_columnCount = $this->getColumn(); ?>
    <div class="row deal-container">
        <?php foreach ($_productCollection as $product): ?>
                <?php $_product = Mage::getModel('catalog/product')->load($product->getId()) ?>
                <div class="item col-md-<?php echo $helper->convertColRow($_columnCount) ?><?php if(($helper->convertColRow($_columnCount)=='4') && (count($_productCollection) == 3 || count($_productCollection) == 5)): ?> col-sm-<?php echo $helper->convertColRow($_columnCount) ?><?php else: ?> col-sm-6<?php endif ?> col-xs-12">
                        <div class="product-sale">
                                <div class="product-content">
                                    <div class="product-hot col-md-5">
                                        <a href="<?php echo $_product->getProductUrl() ?>" title="" class="product-image" >
                                            <img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($size['width'], $size['height']) ?>" alt="<?php echo $this->htmlEscape($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="img-responsive"/>
                                        </a>
                                    </div>
                                    <div class="product-desc col-md-7 no-padding-l">
                                        <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></h2>
                                        <?php echo $this->getPriceHtml($_product, true) ?>
                                        <?php echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                                        <div class="deal-time">
                                            <?php echo $this->getLayout()->createBlock('deals/deals')->setTemplate('mgs/deals/list.phtml')->setProductId($_product->getId())->setData("widgetId",$widgetId)->toHtml(); ?>
                                                <?php $save = $_product->getPrice() - $_product->getFinalPrice() ?>
                                                <?php $percent = round(($save*100)/$_product->getPrice(), 1) ?>
                                            <div class="deals-hot">
                                                <?php echo $percent ?>%
                                                <p><?php echo $this->__('Off') ?></p>
                                            </div>
                                        </div>
                                        <div class="item-info">
                                            <div class="sold">
                                                <?php echo $this->__('Sold:') ?> <span><?php if($this->getSold($_product->getId())): ?><?php echo $this->getSold($_product->getId()) ?> <?php else: ?> <?php echo $this->__('0 item') ?> <?php endif; ?></span>
                                            </div>
                                            <div class="item-left">
                                                <?php $itemLeft = $this->getItemLeft($_product->getId()); ?>
                                                <?php if ($itemLeft != ''): ?>
                                                    <?php if ($itemLeft > 1): ?>
                                                        <?php echo $this->__('Items left:') ?> <span><?php echo $itemLeft ?></span>
                                                    <?php else: ?>
                                                        <?php echo $this->__('Item left:') ?> <span><?php echo $itemLeft ?></span>
                                                    <?php endif ?>
                                                <?php else: ?>
                                                    <?php echo $this->__('Items left:') ?> <span><?php echo $this->__('Unlimited') ?></span>
                                                <?php endif ?>
                                            </div>
                                        </div>
                                        <div class="add-to-cart">
                                            <?php if($_product->isSaleable()): ?>
                                                <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="btn btn-cart btn-primary btn-lg btn-full" onclick="setLocation('<?php echo $this->helper('checkout/cart')->getAddUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
                                            <?php else: ?>
                                                <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                                            <?php endif; ?>
                                        </div>
                                    </div>
                                </div>

                        </div>
                </div>
        <?php endforeach ?>
    </div>
<?php endif ?>
<?php endif ?>