<?php if (Mage::getStoreConfig('deals/general/enabled')): ?>
    <?php $widgetId = $this->getWidgetId(); ?>
    <?php $productCollection = $this->getProductCollection(); ?>
    <?php $helper = $this->helper('mpanel'); ?>
    <?php $size = $helper->convertRatioToSize($this->getProductRatio()) ?>
    <?php $_helper = $this->helper('catalog/output'); ?>
    <?php if (count($productCollection) > 0): ?>
        <div class="block">
            <?php if ($this->getTitle() != ''): ?>
                <div class="block-title">
                    <h2 class="title-name"><?php echo $this->getTitle() ?></h2>
                </div>
            <?php endif ?>
			<div class="row">
            <div id="deal_products" class="owl-carousel deal-carousel block-content">
				<?php $i = 0;
                foreach ($productCollection as $product): ?>
            <?php $_product = Mage::getModel('catalog/product')->load($product->getId()) ?>
                    <div class="product-sale">
                        <div class="product-content">
                            <div class="product-top">
                                <?php echo $this->getLayout()->createBlock('deals/deals')->setTemplate('mgs/deals/list.phtml')->setProductId($_product->getId())->setData("widgetId", $widgetId)->toHtml(); ?>
                                <div class="deals-hot">
                                    <?php $save = $_product->getPrice() - $_product->getFinalPrice() ?>
                                    <?php $percent = round(($save * 100) / $_product->getPrice(), 1) ?>
                                    <?php echo $percent ?>%
                                    <p><?php echo $this->__('OFF') ?></p>
                                </div>
                                <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image">
                                    <img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($size['width'], $size['height']) ?>" alt="<?php echo $this->htmlEscape($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
                                </a>
								<div class="controls">
									<ul class="icon-links">
										<?php if ($this->helper('wishlist')->isAllow()) : ?>
											<li><button type="button" title="<?php echo $this->__('Add to Wishlist') ?>" onclick="setLocation('<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>')"><em class="fa fa-heart"></em></button></li>
										<?php endif; ?>
												<?php if($this->helper('core')->isModuleEnabled('MGS_QuickView') && Mage::getStoreConfig('quickview/general/active')): ?>
											<li class="li-quickview"><button type="button" title="<?php echo $this->__('Quickview') ?>" class="btn-quickview quick-view" onclick="quickView('<?php echo $_product->getProductUrl() ?>'); return false;"><em class="fa fa-search"></em></button></li>
										<?php endif ?>
										<?php if($_compareUrl = Mage::helper('catalog/product_compare')->getAddUrl($_product)): ?>
											<li><button type="button" title="<?php echo $this->__('Add to Compare') ?>" onclick="setLocation('<?php echo $_compareUrl ?>')"><em class="fa fa-retweet"></em></button></li>
										<?php endif; ?>
									</ul>
								</div>
								<div class="overlay-product"></div>
                            </div>
                            <div class="product-desc">
                                <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?></a></h2>
                                <?php echo $this->getPriceHtml($_product, true) ?>
                                <div class="item-info">
                                    <!--div class="sold">
                                <?php echo $this->__('Sold:') ?> <span><?php echo $this->getSold($_product->getId()) ?></span>
                                    </div-->
                                    <!--div class="item-left">
                                    <?php $itemLeft = $this->getItemLeft($_product->getId()); ?>
                                    <?php if ($itemLeft != ''): ?>
                                        <?php if ($itemLeft > 1): ?>
                                            <?php echo $this->__('Items left:') ?> <span><?php echo $itemLeft ?></span>
                                        <?php else: ?>
                                            <?php echo $this->__('Item left:') ?> <span><?php echo $itemLeft ?></span>
                                        <?php endif ?>
                                    <?php else: ?>
                                        <?php echo $this->__('Items left:') ?> <span><?php echo $this->__('Unlimited') ?></span>
            <?php endif ?>
                                    </div-->
                                </div>
                                <div class="add-to-cart">
                                    <?php if($_product->isSaleable()): ?>
                                        <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="btn btn-cart btn-default btn-lg btn-full" onclick="setLocation('<?php echo $this->helper('checkout/cart')->getAddUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
                                    <?php else: ?>
                                        <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                                    <?php endif; ?>
                                </div>
                            </div>
                        </div>
                    </div>	
        <?php endforeach ?>
		</div>
            </div>
        </div>
        <script type="text/javascript">
            initSlider('deal_products', <?php echo $this->getColumn() ?>, <?php echo $this->getAutoPlay() ?>, <?php echo $this->getStopHover() ?>, <?php echo $this->getNavigation() ?>, <?php echo $this->getPagination() ?>);
        </script>
    <?php endif ?>
    <?php
 endif ?>
