<?php
/* * ****************************************************
 * Package   : QuickView
 * Author    : HIEPNH
 * Copyright : (c) 2014
 * ***************************************************** */
?>
<?php $_product = $this->getProduct(); ?>
<?php $buttonTitle = $this->__('Add to Cart'); ?>
<?php if ($_product->isSaleable()): ?>
    <div class="add-to-cart">
        <?php if (!$_product->isGrouped()): ?>
            <label for="qty"><?php echo $this->__('Qty:') ?></label>
            <div class="shop_meta">
                <div class="pull-left">
                    <div class="btn-shop">
                        <div class="form-inline">
                            <div class="form-group">
                                <span onclick="minusQty('qty')"><i class="fa fa-minus"></i></span>
                                <input type="text" class="form-control" title="Qty" value="<?php echo $this->getProductDefaultQty() * 1 ?>" name="qty" id="qty"/>
                                <span onclick="plusQty('qty')"><i class="fa fa-plus"></i></span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        <?php endif; ?>
        <div class="pull-right">
            <div class="btn-shop">
                <button type="button" title="<?php echo $buttonTitle ?>" class="btn-cart btn btn-primary" onclick="ajaxSubmitForm.submit(this)"><span><span><?php echo $buttonTitle ?></span></span></button>        
                &nbsp;<span id="ajax_cart_loader" style="display:none;"><img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>"/></span>
            </div>
        </div>
        <?php echo $this->getChildHtml('', true, true) ?>
        <script type="text/javascript">
            function plusQty(qtyInput){
                if(jQuery('#'+qtyInput).attr('disabled')!='disabled'){
                    qty = $(qtyInput).value;
                    qty = parseInt(qty);
                    qty++;
                    $(qtyInput).value = qty;
                }
            }
    		
            function minusQty(qtyInput){
                if(jQuery('#'+qtyInput).attr('disabled')!='disabled'){
                    qty = $(qtyInput).value;
                    qty = parseInt(qty);
    				
                    if(qty>1){
                        qty--;
                        $(qtyInput).value = qty;
                    }
                }
            }
        </script>
    </div>
<?php endif; ?>
